services:

  gateway:
    build: ./gateway
    ports:
      - "80:80"
    networks:
      - microservice-net
    depends_on:
      - service-a

  # Flask
  service-a:
    build: ./service_a
    networks:
      - microservice-net

networks:
  microservice-net:
    driver: bridge